### ISSUE TITLE
[feature request] different types of links (thumbnail, medium size, ...)?

### ISSUE THREAD

**Issue by poulpor** [CaramelFur/Picsur#18]
I'm a [chevereto-free](https://github.com/rodber/chevereto-free) user and discovered your very promising Picsur project a week ago. The only feature I miss is the availability of different types of links, like thumbnails or medium sized (see the picture of my self hosted server). Do you think it might be an interesting feature to add to Picsur?
I can give you access to my chevereto server if needed.
Thank you and long life to Picsur!

![Capture d’écran 2022-09-22 à 12 01 37](https://user-images.githubusercontent.com/49480426/192225399-81bb9b46-665a-4001-a477-df4e396a182f.png)

**Comment by rubikscraft** [comment]
Hi there, this already a feature. You can use to customize dialog to create a url for a smaller version. Or you can just manually append `?width=200` to the end of the image url. You can change it to any size you want.
And if you dont want it to scale up smaller images, you can make it `?width=200&shrinkonly=true`.

**Comment by poulpor** [comment]
Thank you for those tricks, would you have one to create a link to a clickable thumbnail of the picture?

**Comment by rubikscraft** [comment]
sorry, what do you mean by that?

**Comment by poulpor** [comment]
generate a link to a thumbnail version of the picture that once clicked, will display the full size picture (sorry for my bad english)? Useful for forums, when you don't want to post a full picture but a more discret thumbnail.

**Comment by rubikscraft** [comment]
Ah like that, that isn't really easily doable, since the server has to somehow differentiate between a request from the forum and a request from a user directly. And from what I know there isn't a reliable method to do this, and would require some pretty big restructorizing on the backend.
If the forum allows you to redirect the user to a different url upon clicking the image, it would be more possible, as you could set the click url in the post to the full image.
But even then I wouldn't know how to add something like that cleanly to picsur. As adding more and more url copy bars to the image view page will make it more and more cluttered.
