### ISSUE TITLE
Bug: My Images view renders the wrong image preview

### ISSUE THREAD

**Issue by kaiiiz** [CaramelFur/Picsur#40]
For testing, I uploaded 24 images to the server, and My Images should render the preview in the following order:

![](https://user-images.githubusercontent.com/30596812/226686676-38b2fdca-2cb3-47eb-a874-4a6f2dd5e1c3.jpg)

However, after reloading the page: (animation)

![](https://user-images.githubusercontent.com/30596812/226686882-afaf6652-d82f-4142-827b-9ecbd46500fb.gif)

Some images are not rendered correctly. For instance, the "1" image should render the preview of "1" instead of "13".

![iShot_2023-03-22_01 02 54](https://user-images.githubusercontent.com/30596812/226687322-c153564f-d88b-4fd2-b6dd-02c86d76917c.jpg)

The testing images: [test images.zip](https://github.com/CaramelFur/Picsur/files/11031516/test.images.zip)

**Comment by CaramelFur** [comment]
Hmm, yep that shouldn't happen. I'll take a look.

**Comment by CaramelFur** [comment]
Ok I managed to reproduce the bug once, but now can't get it to happen at all. It's a really weird bug, mainly because the image somehow appears twice, instead of being shuffled wrong.
I will try and look into this later, but considering it's hard to reproduce the bug it will be difficult.
If you have any suggestions as to make the bug happen consistently, that would help.
And thanks for reporting either way 😄

**Comment by krhnoo** [comment]
I can get this to replicate easily. On a GIF heavy gallery slowest loading ones generate as duplicates of previous JPG photo. I can provide gallery you can test this around.

**Comment by CaramelFur** [comment]
@krhnoo Yes that would be great, thanks

**Comment by krhnoo** [comment]
> @krhnoo Yes that would be great, thanks

I've created a sandbox. How should I contact you?

**Comment by CaramelFur** [comment]
@krhnoo sorry for the awfully late reply, haven't had much time recently. But you can contact me via email at contact(at)caramelfur(dot)dev.

**Comment by eshira** [comment]
I have the same issue. A number of photos show the preview for a different photo.

**Comment by NerdAler1** [comment]
I _had_ the same issue. I noticed that the bug only appeared on my primary desktop, and that any other clients did not have this issue. On the desktop I attempted to use different browsers, disable caching, removing all extensions, and reinstalling browsers. None of this fixed it. I had to re image that desktop for other reasons and have not encountered that bug since. I know its not much help, but I figured it might help someone.

**Comment by CaramelFur** [comment]
The new version 0.5.5 should solve this issue, could you verify?

**Comment by CaramelFur** [comment]
Welp, 0.5.5 did not fix the issue, but 0.5.6 does.

**Comment by krhnoo** [comment]
Yeah works for me!
